### PR TITLE
Make modules in file_transfer_protocol importable

### PR DESCRIPTION
**Pull request by mnil2**
#21

### CODE REVIEW

**Review by larshum — CHANGES_REQUESTED** [review]
I think it's ugly to have import statements inside the main method. If you disagree, I think it's fine to keep it there, but the repeated `import socket` statement on lines 4 and 35 in `thealgorithms/file_transfer_protocol/ftp_client_server.py` seems a bit too ugly for me.

But the change itself seems fine, and it does improve the coverage.

**Comment by mnil2** [comment]
I don't disagree. I just didn't want to change their code at all. But I think you're right.

**Comment by mnil2** [comment]
Actually, this branch doesn't appear to pass linting. I'll have to fix this

**Comment by mnil2** [comment]
OK I think this is good now

**Review by larshum — APPROVED** [review]

**Pull request merged**
